name: Hello World
author: Ryan Ng
description: hellow world testing

inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: Ryan

outputs:
  time:
    description: 'The time we greeted you'

runs:
  using: 'node16'
  main: 'dist/index.js'


  