on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/hello
        with:
          who-to-greet: "Eeyore"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
